config/routes.rb
Ebid41::Application.routes.draw do


  resources :photos

  # get "sessions/new"
  # 
  # get "admin/nav"

  devise_for :users, path: :account, controllers: {sessions: "sessions"}
  resources :users, :shallow => true do
    resources :ratings, :only => :index
    resources :entries
  end

  scope 'buyer' do
    get 'dashboard' => 'buyer#dashboard', as: :buyer_dashboard
    get 'entries(/:s)' => 'buyer#entries', as: :buyer_entries
    get 'show/:id' => 'buyer#show', as: :buyer_show
    get 'show/:id/print' => 'buyer#print', as: :print_entry
    get 'reactivate/:id' => 'buyer#reactivate', as: :buyer_reactivate
    get 'orders(/:s(/:id))' => 'buyer#orders', as: :buyer_orders
    get 'fees(/:t)' => 'buyer#fees', as: :buyer_fees
    get 'messages(/:t)' => 'buyer#messages', as: :buyer_messages
    get 'surrender/:id' => 'buyer#surrender', as: :surrender_parts
    post 'surrender_letter/:id' => 'buyer#surrender_letter', as: :surrender_letter
  end

  scope 'seller' do
    get 'dashboard' => 'seller#dashboard', as: :seller_dashboard
    get 'entries(/:s)' => 'seller#entries', as: :seller_entries
    get 'worksheet' => 'seller#worksheet', as: :seller_worksheet
    get 'show/:id' => 'seller#show', as: :seller_show
    get 'bids' => 'seller#bids', as: :seller_bids
    get 'orders(/:s(/:id))' => 'seller#orders', as: :seller_orders
    get 'fees(/:t)' => 'seller#fees', as: :seller_fees
    get 'messages(/:t)' => 'seller#messages', as: :seller_messages
  end
  
  scope 'admin' do
    get 'dashboard' => 'admin#dashboard', as: :admin_dashboard
    get 'update_ratios' => 'admin#update_ratios', as: :update_ratios
    get 'expire_entries' => 'admin#expire_entries', as: :expire_entries
    get 'tag_payments' => 'admin#tag_payments', as: :tag_payments
    get 'send_payment_reminder' => 'admin#send_payment_reminder', as: :send_payment_reminder
    get 'delivery_reminder' => 'admin#delivery_reminder', as: :delivery_reminder
    get 'fix' => 'admin#fix', as: :fix
  end


  get "cart/add"
  get "cart/remove"
  get "cart/clear"

  resources :variances, only: :index do
    get :summarize, on: :collection
  end
  resources :entries, shallow: true do
    member do
      get :put_online
      get :reveal
      get :relist
      get :reactivate
      get :rebid
      get :print
      get :add_photos
      get :attach_photos
      put :save_photos
    end
    resources :variances, except: :index
  end

  resources :var_items
  resources :var_companies do
    get :add, on: :collection
    get :close, on: :collection
  end

  scope 'fees' do
    get '/:t' => 'fees#index', as: :fees
    get '/:t/print' => 'fees#print', as: :print_fees
  end
  resources :fees

  resources :messages do
    collection do
      get :view
      get :close
    end
 end

  resources :orders do
    member do
      get :accept
      get :change_status
      put :buyer_paid
      get :print
      get :cancel
      put :confirm_cancel
      get :uncancel
      put :confirm_uncancel
    end
    collection do
      get :auto_paid
    end
    resources :ratings
  end
  resources :ratings, shallow: true do
    get :auto, on: :collection
  end

  resources :bids do
    collection do
      post :accept
    end
    get :revise, on: :member
  end

  resources :line_items do
    collection do
      get :add
      get :cancel
      get :add_specs
      post :save_specs
    end
  end

  resources :profiles

  resources :ranks

  resources :branches

  resources :companies do
    get :selected, on: :member
  end

  resources :car_parts do
    collection do
      get :search
      # get :add_more
      get :cancel
    end
  end


  resources :cities

  resources :car_variants do
    member do
      get :transfer
      put :confirm_transfer
    end
  end

  resources :car_brands do
    get :selected, on: :member
  end
  
  resources :car_models do
    get :selected, on: :member
  end
  
  # authenticated :user do
  #   root :to => 'home#index'
  # end
  root :to => 'home#index'
end

app/controllers/seller_controller.rb
class SellerController < ApplicationController
  before_filter :search_car_models, only: [:entries, :bids, :orders]
  before_filter :check_user_enabled

  def dashboard
    @presenter = SellerPresenter.new(current_user)
    @messages = Message.where(receiver_company_id: current_user.company).order('id DESC')
  end
  
  def entries
    @q ||= Entry.find_status(params[:s]).search(params[:q])
    @entries = @q.result.joins{company.friends}.where(:friendships => { :friend_id => current_user.company.id}).includes(:photos, :car_brand, :car_model, :line_items, :bids, :messages).page(params[:page]).per_page(8)

  end

  def worksheet
    # raise params.to_yaml
    if params[:entries] 
      @entries = Entry.where(:id => params[:entries])
    else
      @entries = Entry.online.active.unexpired.joins{company.friends}.where(:friendships => { :friend_id => current_user.company.id}).includes(:line_items)
    end
    @company = current_user.company
    render layout: 'print'
  end

  def bids
    @q = Bid.unscoped.search(params[:q])
    @bids = @q.result.where(user_id: current_user.company.users).includes([:entry => [:car_brand, :car_model]], [:line_item => :car_part], :user).order('created_at DESC').page(params[:page]).per_page(15)
  end

  def show
    @entry = Entry.find(params[:id], include: [:line_items => [:car_part, :bids]])
    unless @entry.company.friends.include?(current_user.company) || can?(:access, :all)
      flash[:error] = "Sorry, you are not allowed to access that Entry."
      redirect_back_or_default seller_dashboard_path
    end
  end

  def orders
    @q = Order.search(params[:q])
    @all_orders ||= @q.result.find_status(params[:s]).by_this_seller(current_user.company)
    @orders = @all_orders.includes([:entry => [:car_brand, :car_model, :user]], :company, :messages).page(params[:page]).per_page(10)
 
    @buyer_company = Company.find(params[:q][:company_id_matches]).nickname if params[:q] && params[:q][:company_id_matches].present?
  end

  def fees
    @q = Fee.find_type(params[:t]).by_this_seller(current_user.company).filter_period(params[:q]).search(params[:q])
    @all_fees ||= @q.result
    @fees = @all_fees.includes([:entry => [:user, :car_brand, :car_model]], [:line_item => :car_part], [:seller_company], :order).page(params[:page]).per_page(20)

    buyer_present?
    seller_present?
  end
  
  def messages
    @q = Message.restricted(current_user.company).search(params[:q])
    @messages = @q.result.order('created_at DESC').page(params[:page]).per_page(20)
  end
  
  
end

app/helpers/seller_helper.rb
module SellerHelper
  def supplier_bid_rate(entry, bids)
    if bids.present?
  	  "You bidded #{bids.collect(&:line_item_id).uniq.count} of #{pluralize entry.line_items.size, 'part'}"
	  else
	    content_tag :span, "You have no bids", class: 'highlight'
    end
  end
end

app/views/seller/_bid_box_temp.html.erb
<% %w(original replacement surplus).each do |t| %>
	<td class="<%= t[0..3] %> bids span2 txtcenter">
		<%#= bid_box_helper item.id, t if item.is_online %>
		<%= bid_box_helper(item.id, t, current_user) if item.is_online %>
		<div class="bid-container">
			<% item.bids.group_by(&:bid_type).each do |type, bids| %>
				<% bids.group_by(&:user).each do |user, bs| %>

					<% if t == type && current_user.company.users.include?(user) %>
						<% own_bid = bs.last %>
						<%= render own_bid if own_bid %>									
						<%= render 'seller/winning_bid', item: item, own_bid: own_bid, bids: bids unless current_user.id == 67 %>
					<% end %> 

				<% end %>
			<% end %>
		</div>
	</td>
<% end %>

app/views/seller/_invalid_bid_msg.html.erb
<%= content_tag :div, 'Invalid Bid', class: 'invalid label label-important' %>

app/views/seller/_nav.html.erb
<ul class="nav">
	<%= content_tag :li, link_to('SELLER', seller_dashboard_path), class: 'active' %>
	<%= content_tag :li, class: "dropdown #{drop_active?('entries')}" do %>
		<%= drop_link 'Entries' %>
		<ul class="dropdown-menu">
			<%= nav_link('Online', seller_entries_path(s: 'online')) %>
			<%= nav_link('For Decision', seller_entries_path(s: 'for-decision')) %>
			<%= nav_link('All Entries', seller_entries_path(s: 'all')) %>
		</ul>
	<% end %>
	<%= nav_link('Bids', seller_bids_path) %>
	<%= content_tag :li, class: "dropdown #{drop_active?('orders')}" do %>
		<%= drop_link 'Orders' %>
		<ul class="dropdown-menu">
			<%= nav_link('New', seller_orders_path(s: 'new')) %>
			<%= nav_link('For Delivery', seller_orders_path(s: 'for-delivery')) %>
			<%= content_tag :li, '', class: 'divider' %>
			<%= nav_link('Delivered: Within Term', seller_orders_path(s: 'delivered')) %>
			<%= nav_link('Delivered: Overdue', seller_orders_path(s: 'overdue')) %>
			<%= content_tag :li, '', class: 'divider' %>
			<%= nav_link('Paid: Unconfirmed', seller_orders_path(s: 'unconfirmed')) %>
			<%= nav_link('Paid: Confirmed', seller_orders_path(s: 'paid')) %>
			<%= nav_link('Closed', seller_orders_path(s: 'closed')) %>
			<%= content_tag :li, '', class: 'divider' %>
			<%= nav_link('Cancelled', seller_orders_path(s: 'cancelled')) %>
		</ul>
	<% end %>
	<%= content_tag :li, class: "dropdown #{drop_active?('fees')}" do %>
		<%= drop_link 'Fees' %>
		<ul class="dropdown-menu">
			<%= nav_link("Seller's Fees", seller_fees_path(t: 'sf')) %>
			<%= nav_link('Decline Fees', seller_fees_path(t: 'bf')) %>
		</ul>
	<% end %>
	<%= nav_link('Messages', seller_messages_path) %>
</ul>

app/views/seller/_parts_list.html.erb
<div id="bidding-message" class="txtcenter"></div>

<%= form_tag bids_path(:entry_id => @entry), remote: true do %>
	<div id="" class="well">
		<table class="table">
			<%= render 'entries/thead_show' %>

			<% LineItem::STATUS_TAGS.each do |tag| %>
				<% @entry.line_items.includes(:car_part, :bids).group_by(&:status).sort.each do |status, line_items| %>
					
					<% if status == tag %>
						<tr>
							<%= content_tag :td, status, colspan: 4, class: 'label label-inverse' %>
						</tr>
				
						<% line_items.each_with_index do |item, index| %>
						<tr id="<%= item.id %>">
							<td class="span4">
								<%= content_tag :div, index + 1, class: 'index'  %>
								<div class="parts">
									<%= content_tag :p, item %>
									<%= "#{content_tag :code, 'Details: ' + item.specs, class: 'small'}".html_safe if item.specs.present? %>
									<%= content_tag :p, (link_with_icon "PO# #{item.order_id}", item.order, 'shopping-cart', "btn btn-mini btn-success", true) if item.order && item.order.seller_id == current_user.id %>
								</div>
							</td>
					
							<% %w(original replacement surplus).each do |t| %>
								<td class="<%= t[0..3] %> bids span2 txtcenter">
									<% own_bid = item.bids.where(user_id: current_user.company.users, bid_type: t) %>
									<% if own_bid.present? %>
										<%= render own_bid %>
										<%= render 'seller/winning_bid', item: item, own_bid: own_bid, bids: item.bids.where(bid_type: t) unless current_user.id == 67 %>
									<% else %>
										<%= bid_box_helper(item.id, t) if item.is_online %>
									<% end %>
								</td>
							<% end %>
						</tr>
						<% end %>
					<% end %>
					
				<% end %>
			<% end %>
		</table>
	</div>

	<div class="well">
		<%= link_to 'Other Online Entries', seller_entries_path(s: 'online'), class: 'btn' %>
		<%= submit_tag "Submit Bids", class: 'btn btn-success pull-right' if @entry.is_online %>
	</div>
<% end %>

<% content_for :javascripts do %>
		$('.close').tooltip();
<% end %>

app/views/seller/_winning_bid.html.erb
<% if !item.is_online %>
	<% lo_bid = bids.not_cancelled.last %>
	<% if lo_bid != own_bid  %>
		<%= content_tag :code, class: "small" do %>
			<%= content_tag :span, currency(lo_bid.amount) %>
			<%= content_tag :em, 'winner' %>
		<% end %>
	<% end %>
<% end %>

app/views/seller/bids.html.erb
<% title "#{current_user.nickname}'s Bids".html_safe %>
<div class="navbar search">
  <div class="navbar-inner">
	<%= content_tag :span, 'Search', class: 'brand' %>
		<%= search_form_for @q, url: request.path, html: { class: 'navbar-search' } do |f| %>
		  <%= f.text_field :entry_plate_no_cont, class: 'input-small', placeholder: 'Plate Number' %>
		  <%= f.grouped_collection_select :car_brand_id_eq, CarOrigin.includes(:car_brands), :car_brands, :name, :id, :name, { include_blank: 'Brand' }, id: 'veh-brand' %>
		  <%= f.collection_select :entry_car_model_id_eq, @car_models, :id, :name, { include_blank: 'Model' }, id: 'veh-model' %>
			<%= f.button 'Go!', class: 'btn btn-primary' %>
			<%= refresh_button %>
		<% end %>
  </div>
</div>

<%= content_tag :div, page_entries_info(@bids), class: 'page-info' %>

<% if @bids.present? %>
<%= content_tag :table, class: 'table table-condensed' do %>
	<thead>
		<%= content_tag :th, '', colspan: 2 %>
		<%= th_bidtype_helper('Original') %>
		<%= th_bidtype_helper('Replacement') %>
		<%= th_bidtype_helper('Surplus') %>
	</thead>

	<% @bids.group_by{ |b| b.created_at.beginning_of_day }.each do |date, grouped_bids| %>
		<%= content_tag :tr do %>
			<%= content_tag :td, colspan: 5, class: 'label label-inverse' do %>
				<%= content_tag :b, regular_date(date, 'day') %>
			<% end %>
		<% end %>
		
		<% grouped_bids.group_by(&:entry).each do |entry, bids| %>

			<%= content_tag :tr do %>
				<%= content_tag :td, class: 'span4', rowspan: bids.collect(&:line_item).uniq.count + 1  do %>
					<%#= content_tag :span, entry.show_status, class: "label #{entry.status_color}" %>
		      <%= content_tag :p, link_to(entry.model_name, seller_show_path(entry)), class: 'lead'  %>
					<%= content_tag :p, entry.plate_no %>
					<p>
						<%= parts_bidded(entry, current_user) %>
						<%= content_tag :span, "#{pluralize entry.line_items.size, 'item'}".html_safe, class: 'small' %>
					</p>
				<% end %>
			<% end %>
		
			<% bids.group_by(&:line_item).each do |item, bts| %>
				<%= content_tag :tr do %>
					<%= content_tag :td, class: 'span4' do %>
						<%= content_tag :p, item %>
						<%= content_tag :code, item.specs if item.specs.present?  %>
					<% end %>
					<%= content_tag :td, class: 'span2 txtcenter bids' do %>
						<% bts.map {|b| b if b.orig? }.each do |bid| %>
							<%#= bid_amount_helper bid if bid %>
							<%= render bid if bid %>
						<% end %>
					<% end %>
					<%= content_tag :td, class: 'span2 txtcenter bids' do %>
						<% bts.map {|b| b if b.rep? }.each do |bid| %>
							<%= render bid if bid %>
						<% end %>
					<% end %>
					<%= content_tag :td, class: 'span2 txtcenter bids' do %>
						<% bts.map {|b| b if b.surp? }.each do |bid| %>
							<%= render bid if bid %>
						<% end %>
					<% end %>
				
				<% end %>
			<% end %> 
			
		<% end %> 

	<% end %> 
	
<% end %> 

<%= will_paginate @bids, inner_window: 2 %>
<% end %>

app/views/seller/dashboard.html.erb
<% title 'Seller Dashboard' %>
<% subtitle current_user.fullname %>

<div class="alert">
	<div class="span3">
		<%= content_tag :b, current_user.company.name.upcase %>
	</div>
	<div class="span4">
		<%= star_images(@presenter.company_rating.average('stars').to_f) %>
		<%= content_tag :p, ('based on ' + (link_to (pluralize @presenter.company_rating.count, 'rating'), user_ratings_path('all'))).html_safe %>
	</div>
	<div class="span4">
		<%= content_tag :b, 'Average Delivery Time' %>
		<%= content_tag :span, (pluralize @presenter.average_delivery_time, 'day'), class: 'lead' %>
	</div>
	<%= clearfix_div %>
</div>

<div class="row">
	<div class="span3">
		<table class="table table-bordered table-condensed">
			<thead>
				<tr>
					<%= content_tag :th, 'Entries', colspan: 2, class: 'label label-inverse txtcenter' %>
				</tr>
			</thead>
			<tbody>
				<tr>
					<%= content_tag :td, 'Online' %>
					<td class="txtright">
						<%= content_tag :span, @presenter.online_entries.count, class: 'lead' %>
						<%= link_with_icon '', seller_entries_path(s: 'online'), 'play', 'btn-small btn-primary', true %>
					</td>
				</tr>
				<tr>
					<%= content_tag :td, 'For Decision' %>
					<td class="txtright">
						<%= content_tag :span, @presenter.for_decision_entries.count, class: 'lead' %>
						<%= link_with_icon '', seller_entries_path(s: 'for-decision'), 'play', 'btn-small' %>
					</td>
				</tr>
				<tr class="alert-info">
					<td colspan="2" class="txtcenter">
						<%= content_tag :b, 'Bidding Ratio' %>
						<%= content_tag :span, @presenter.bidding_ratio, class: 'lead' %>
						<p class="small">
							<%= @presenter.bidding_ratio_details %>
							(<%= Time.now.year %>)
						</p>
					</td>
				</tr>
				<% if @presenter.bidding_ratio.present? && @presenter.bidding_ratio < "25%" %>
					<tr class="alert-success">
						<td colspan="2" class="txtcenter">
							<%= content_tag :p, 'Tip', class: 'label label-success' %>
							<%= content_tag :span, "Target a bidding ratio of <b>at least 25%</b> to get a steady number of orders. So keep on bidding!".html_safe %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	
	<div class="span4">
		<table class="table table-bordered table-condensed">
			<thead>
				<tr>
					<%= content_tag :th, 'Orders', colspan: 3, class: 'label label-inverse txtcenter' %>
				</tr>
			</thead>
			<tbody>
				<tr>
					<%= content_tag :td, 'New' %>
					<%= content_tag :td, @presenter.new_orders.count, class: 'txtright' %>
					<td class="txtright">
						<%= content_tag :span, (currency @presenter.new_orders.sum(:order_total), 'P '), class: 'lead' %>
						<%= link_with_icon '', seller_orders_path(s: 'new'), 'play', 'btn-small btn-primary', true unless @presenter.new_orders.blank?%>
					</td>
				</tr>
				<tr>
					<%= content_tag :td, 'Delivered' %>
					<%= content_tag :td, @presenter.delivered.count, class: 'txtright' %>
					<td class="txtright">
						<%= content_tag :span, (currency @presenter.delivered.sum(:order_total), 'P '), class: 'lead' %>
						<%= link_with_icon '', seller_orders_path(s: 'delivered'), 'play', 'btn-small' unless @presenter.delivered.blank?%>
					</td>
				</tr>
				<tr<%= " class=alert-error" unless @presenter.overdue.blank? %>>
					<%= content_tag :td, 'Overdue' %>
					<%= content_tag :td, @presenter.overdue.count, class: 'txtright' %>
					<td class="txtright">
						<%= content_tag :span, (currency @presenter.overdue.sum(:order_total), 'P '), class: 'lead' %>
						<%= link_with_icon '', seller_orders_path(s: 'overdue'), 'play', 'btn-small btn-danger', true unless @presenter.overdue.blank? %>
					</td>
				</tr>
				<tr class="alert-success">
					<td colspan="3" class="txtcenter">
						<%= content_tag :b, 'Total orders you got through E-Bid: ' %>
						<%= content_tag :span, (currency @presenter.total_orders, 'P'), class: 'lead' %>
						<%= content_tag :i, '', class: 'icon-thumbs-up' if @presenter.total_orders > 0 %>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
	
	<%= render 'messages/for_dashboard', link: seller_messages_path %>
</div>

app/views/seller/entries.html.erb
<% title "Entries#{': ' + params[:s].titleize if params[:s]}" %>
<%= render 'entries/search_bar', path: seller_entries_path %>


<%= form_tag seller_worksheet_path, method: :get do %>

	<% if params[:s] == 'online' && @entries.present? %>
		<div class="alert">
			<%= submit_tag 'Print Bidding Worksheet', class: 'btn btn-large pull-right' %>
			<%= content_tag :p, "You can print a bidding worksheet. Use the checkboxes to select the vehicles you want,<br> or just leave them blank to select all.".html_safe %>
		</div>
	<% end %>

	<%= content_tag :div, page_entries_info(@entries), class: 'page-info' %>

	<%= content_tag :table, class: 'table table-condensed' do %>

		<% @entries.group_by{ |e| e.updated_at.beginning_of_day }.each do |date, entries| %>
			<tr>
				<%= content_tag :td, colspan: 6, class: 'label label-inverse' do %>
					<%= content_tag :b, regular_date(date, 'day') %>
				<% end %>
			</tr>

			<% entries.group_by(&:status).each do |status, es| %>
				<% es.each do |entry| %>
				<tr>
					<%= content_tag :td, class: 'span4' do %>
			      <%= content_tag :p, link_to(entry.model_name, seller_show_path(entry)), class: 'lead vehicle' %>
						<%= content_tag :p, entry.plate_no, class: 'muted' %>
						<%#= content_tag :p, entry.user, class: 'muted' %>
					<% end %>

					<%= content_tag :td, class: 'span2' do %>
						<% if entry.is_online %>
							<%= link_to 'Bid Here', seller_show_path(entry), class: 'btn btn-primary' %>
						<% else %>
							<%= link_to 'View', seller_show_path(entry), class: 'btn' %>
						<% end %>
						<%= check_box_tag 'entries[]', entry.id if params[:s] == 'online' %>
					<% end %>

					<%= content_tag :td, class: "span3" do %>
						<%= progress_bar_helper(percentage(entry.bid_rate_by_supplier(current_user))) if entry.bid_rate_by_supplier(current_user) > 0 %>
						<p>
							<%= parts_bidded(entry, current_user) %>
							<%= content_tag :span, "#{pluralize entry.line_items.size, 'item'}".html_safe, class: 'pull-right' %>
						</p>
					<% end %>

					<%= content_tag :td, class: 'span2 txtcenter' do %>
						<%= entry_status_helper(entry) %>
					<% end %>

					<%= content_tag :td, class: 'span1 txtright' do %>
						<p>
							<%= content_tag :span, entry.id, class: 'muted small' %>
						</p>
						<%= tooltip_helper entry.photos.size, 'photo', 'camera' %>
						<%= tooltip_helper entry.messages.restricted(current_user.company).size, 'message', 'comment', 'highlight' if entry.messages.restricted(current_user.company).present? %>
					<% end %>
				</tr>
				<% end %>
			<% end %>

		<% end %>
	<% end %>

<% end %>

<%= will_paginate @entries, inner_window: 2 %>

app/views/seller/messages.html.erb
<% title "Messages" %>
<%= render 'messages/search_bar', path: seller_messages_path %>

<%= render 'messages/table_index' %>
<%= will_paginate @messages %>

app/views/seller/orders.html.erb
<% title "#{current_user.nickname}'s Orders#{': ' + params[:s].titleize if params[:s]}".html_safe %>
<%= render 'orders/search_bar', path: seller_orders_path %>

<%= content_tag :h2, class: 'row' do %>
	<%= content_tag :span, currency(@all_orders.total_orders, 'P '), class: 'span6' %>
	<%#= display_buyer_company %>
<% end %>

<%= render 'orders/index_list' %>

app/views/seller/show.html.erb
<% title @entry.model_name %>
<% subtitle "#{@entry.variant} (#{@entry.plate_no})" %>

<section id="vehicle-info">
	<%= render 'entries/info_vehicle' %>
</section>
<%= render 'entries/public_messages' if @entry.messages.pub.present? %>
<section class="photo-set alert">
	<% unless @entry.photos.blank? %>
		<ul class="unstyled">
			<%= content_tag :li, 'Click on photos to enlarge.' %>
			<% @entry.photos.each do |photo| %>
				<%= content_tag :li do %>
				<%= link_to((image_tag photo.photo.url(:tiny), alt: "Photo of #{@entry.plate_no}"), photo.photo.url(:large), rel: "#{@entry.id}", class: 'photo') %>
				<% end %>
			<% end %>
		</ul>	
	<% else %>
		<%= content_tag :em, 'No photos submitted.' %> 
		<%= link_with_icon('Upload Photos', edit_entry_path(@entry), 'pencil', 'btn-info', true) %>
	<% end %>
</section>


<section id="parts-list">
	<% if @entry.is_online %>
		<p>
			<%= content_tag :span, 'Instructions', class: 'label label-important' %>
			Input your best bids on the boxes provided below, then press "Enter" to submit.
		</p>
	<% end %>
	<%= render 'seller/parts_list' %>
</section>

<section id="time-line">
	<%= content_tag :ul, class: 'breadcrumb small' do %>
		<% Entry::TAGS_FOR_SIDEBAR.each do |tag| %>
			<%= get_date_for_sidebar(@entry, tag) %>
		<% end %>
	<% end %>
</section>

<% content_for :javascripts2 do %>
	<% stylesheet 'fancybox/jquery.fancybox-1.3.4.css' %>
	<%= javascript_include_tag 'fancybox/jquery.fancybox-1.3.4.pack.js' %>
	<%= javascript_include_tag 'fancybox/jquery.mousewheel-3.0.4.pack.js' %>

	<script type="text/javascript" charset="utf-8">
	$('a.photo').fancybox({
		'transitionIn'		: 'elastic',
		'transitionOut'		: 'elastic',
		'titlePosition' 	: 'over',
		'titleFormat'		: function(title, currentArray, currentIndex, currentOpts) {
			return '<span id="fancybox-title-over">Image ' + (currentIndex + 1) + ' / ' + currentArray.length + (title.length ? ' &nbsp; ' + title : '') + '</span>';
		}
	});
	</script>
<% end %>

app/views/seller/worksheet.html.erb
<table class="table table-bordered">
	<thead>
    <%= content_tag :th, 'Vehicle', class: 'span4' %>
    <%= content_tag :th, 'Parts', class: 'span4' %>
    <%= content_tag :th, 'Orig', class: 'span3 txtcenter' %>
    <%= content_tag :th, 'Rep', class: 'span3 txtcenter' %>
    <%= content_tag :th, 'Surp', class: 'span3 txtcenter' %>
	</thead>
	<% for entry in @entries %>
		<tr>
			<td class="vehicle" rowspan=<%= entry.line_items.size + 1%>>
				<%= content_tag :p, "#{content_tag :b, entry.model_name}".html_safe %>
				<%= content_tag :em, entry.variant, class: 'small' %>
				<%= content_tag :p, "Plate: #{entry.plate_no}" %>
				<%= content_tag :p, "Serial: #{entry.serial_no}" %>
				<%= content_tag :p, "Motor: #{entry.motor_no}" %>
			</td>
		</tr>
		<% for item in entry.line_items %>
		<tr>
	    <%= content_tag :td, item %>
	    <%= content_tag :td %>
	    <%= content_tag :td %>
	    <%= content_tag :td %>
		</tr>
		<% end %>
	<% end %>
</table>