config/routes.rb
Ebid41::Application.routes.draw do


  resources :photos

  # get "sessions/new"
  # 
  # get "admin/nav"

  devise_for :users, path: :account, controllers: {sessions: "sessions"}
  resources :users, :shallow => true do
    resources :ratings, :only => :index
    resources :entries
  end

  scope 'buyer' do
    get 'dashboard' => 'buyer#dashboard', as: :buyer_dashboard
    get 'entries(/:s)' => 'buyer#entries', as: :buyer_entries
    get 'show/:id' => 'buyer#show', as: :buyer_show
    get 'show/:id/print' => 'buyer#print', as: :print_entry
    get 'reactivate/:id' => 'buyer#reactivate', as: :buyer_reactivate
    get 'orders(/:s(/:id))' => 'buyer#orders', as: :buyer_orders
    get 'fees(/:t)' => 'buyer#fees', as: :buyer_fees
    get 'messages(/:t)' => 'buyer#messages', as: :buyer_messages
    get 'surrender/:id' => 'buyer#surrender', as: :surrender_parts
    post 'surrender_letter/:id' => 'buyer#surrender_letter', as: :surrender_letter
  end

  scope 'seller' do
    get 'dashboard' => 'seller#dashboard', as: :seller_dashboard
    get 'entries(/:s)' => 'seller#entries', as: :seller_entries
    get 'worksheet' => 'seller#worksheet', as: :seller_worksheet
    get 'show/:id' => 'seller#show', as: :seller_show
    get 'bids' => 'seller#bids', as: :seller_bids
    get 'orders(/:s(/:id))' => 'seller#orders', as: :seller_orders
    get 'fees(/:t)' => 'seller#fees', as: :seller_fees
    get 'messages(/:t)' => 'seller#messages', as: :seller_messages
  end
  
  scope 'admin' do
    get 'dashboard' => 'admin#dashboard', as: :admin_dashboard
    get 'update_ratios' => 'admin#update_ratios', as: :update_ratios
    get 'expire_entries' => 'admin#expire_entries', as: :expire_entries
    get 'tag_payments' => 'admin#tag_payments', as: :tag_payments
    get 'send_payment_reminder' => 'admin#send_payment_reminder', as: :send_payment_reminder
    get 'delivery_reminder' => 'admin#delivery_reminder', as: :delivery_reminder
    get 'fix' => 'admin#fix', as: :fix
  end


  get "cart/add"
  get "cart/remove"
  get "cart/clear"

  resources :variances, only: :index do
    get :summarize, on: :collection
  end
  resources :entries, shallow: true do
    member do
      get :put_online
      get :reveal
      get :relist
      get :reactivate
      get :rebid
      get :print
      get :add_photos
      get :attach_photos
      put :save_photos
    end
    resources :variances, except: :index
  end

  resources :var_items
  resources :var_companies do
    get :add, on: :collection
    get :close, on: :collection
  end

  scope 'fees' do
    get '/:t' => 'fees#index', as: :fees
    get '/:t/print' => 'fees#print', as: :print_fees
  end
  resources :fees

  resources :messages do
    collection do
      get :view
      get :close
    end
 end

  resources :orders do
    member do
      get :accept
      get :change_status
      put :buyer_paid
      get :print
      get :cancel
      put :confirm_cancel
      get :uncancel
      put :confirm_uncancel
    end
    collection do
      get :auto_paid
    end
    resources :ratings
  end
  resources :ratings, shallow: true do
    get :auto, on: :collection
  end

  resources :bids do
    collection do
      post :accept
    end
    get :revise, on: :member
  end

  resources :line_items do
    collection do
      get :add
      get :cancel
      get :add_specs
      post :save_specs
    end
  end

  resources :profiles

  resources :ranks

  resources :branches

  resources :companies do
    get :selected, on: :member
  end

  resources :car_parts do
    collection do
      get :search
      # get :add_more
      get :cancel
    end
  end


  resources :cities

  resources :car_variants do
    member do
      get :transfer
      put :confirm_transfer
    end
  end

  resources :car_brands do
    get :selected, on: :member
  end
  
  resources :car_models do
    get :selected, on: :member
  end
  
  # authenticated :user do
  #   root :to => 'home#index'
  # end
  root :to => 'home#index'
end

app/views/admin/_nav.html.erb
<ul class="nav">
	<%= content_tag :li, class: "dropdown #{drop_active_cont?('entries')}" do %>
		<%= drop_link 'Entries' %>
		<ul class="dropdown-menu">
			<%= nav_link('Create', new_user_entry_path(current_user)) %>
			<%= nav_link('Drafts', entries_path(s: 'new')) %>
			<%= content_tag :li, '', class: 'divider' %>
			<%= nav_link('Online', entries_path(s: 'online')) %>
			<%= nav_link('For Decision', entries_path(s: 'for-decision')) %>
			<%= content_tag :li, '', class: 'divider' %>
			<%= nav_link('With Orders', entries_path(s: 'ordered')) %>
			<%= nav_link('Declined', entries_path(s: 'declined')) %>
			<%= nav_link('Recently Expired', entries_path(s: 'expired')) %>
			<%= content_tag :li, '', class: 'divider' %>
			<%= content_tag :li, link_to('All Entries', entries_path) %>
		</ul>
	<% end %>
	<%= nav_link('Bids', bids_path) %>
	<%= content_tag :li, class: "dropdown #{drop_active_cont?('orders')}" do %>
		<%= drop_link 'Orders' %>
		<ul class="dropdown-menu">
			<%= nav_link('New', orders_path(s: 'new')) %>
			<%= nav_link('For Delivery', orders_path(s: 'for-delivery')) %>
			<%= content_tag :li, '', class: 'divider' %>
			<%= nav_link('Delivered: Within Term', orders_path(s: 'delivered')) %>
			<%= nav_link('Delivered: Overdue', orders_path(s: 'overdue')) %>
			<%= content_tag :li, '', class: 'divider' %>
			<%= nav_link('Paid: Unconfirmed', orders_path(s: 'unconfirmed')) %>
			<%= nav_link('Paid: Confirmed', orders_path(s: 'paid')) %>
			<%= nav_link('Closed', orders_path(s: 'closed')) %>
			<%= content_tag :li, '', class: 'divider' %>
			<%= nav_link('Cancelled', orders_path(s: 'cancelled')) %>
		</ul>
	<% end %>
	<%= content_tag :li, class: "dropdown #{drop_active_cont?('fees')}" do %>
		<%= drop_link 'Fees' %>
		<ul class="dropdown-menu">
			<%= nav_link("Seller's Fees", fees_path(t: 'sf')) %>
			<%= nav_link('Decline Fees', fees_path(t: 'bf')) %>
		</ul>
	<% end %>
	<%= content_tag :li, class: "dropdown #{drop_active?('entries')}" do %>
		<%= drop_link 'Tables' %>
		<ul class="dropdown-menu">
			<%= nav_link('Messages', messages_path) %>
			<%= nav_link('Users', users_path) %>
			<%= content_tag :li, '', class: 'divider' %>
			<%= nav_link('Brands', car_brands_path) %>
			<%= nav_link('Models', car_models_path) %>
			<%= nav_link('Variants', car_variants_path) %>
			<%= nav_link('Parts', car_parts_path) %>
			<%= content_tag :li, '', class: 'divider' %>
			<%= nav_link('Companies', companies_path) %>
			<%= nav_link('Branches', branches_path) %>
			<%= nav_link('Cities', cities_path) %>
			<%= content_tag :li, '', class: 'divider' %>
			<%= nav_link('Ratings', ratings_path) %>
			<%= nav_link('Variances', variances_path) %>
		</ul>
	<% end %>
	<%= content_tag :li, class: "dropdown" do %>
		<%= drop_link 'Utilities' %>
		<ul class="dropdown-menu">
			<%= nav_link('Update Performance Ratios', update_ratios_path) %>
			<%= nav_link('Expire Entries', expire_entries_path) %>
			<%= nav_link('Tag Payments', tag_payments_path) %>
			<%= content_tag :li, '', class: 'divider' %>
			<%= nav_link('Send Payment Reminders', send_payment_reminder_path) %>
			<%= nav_link('Send Delivery Reminders', delivery_reminder_path) %>
			<%= content_tag :li, '', class: 'divider' %>
			<%= nav_link('Fix Entries', fix_path) %>
			<%= nav_link 'Automatic Ratings', auto_ratings_path %>
		</ul>
	<% end %>
</ul>

app/views/admin/dashboard.html.erb
<% title 'Admin Dashboard' %>
<% subtitle current_user.fullname %>

<div class="row">
	<div class="span3">
		<table class="table table-bordered table-condensed">
			<thead>
				<tr>
					<%= content_tag :th, 'Entries', colspan: 2, class: 'label label-inverse txtcenter' %>
				</tr>
			</thead>
			<tbody>
				<tr>
					<%= content_tag :td, 'Drafts' %>
					<td class="txtright">
						<%= content_tag :span, @presenter.draft_entries.count, class: 'lead' %>
						<%= link_with_icon '', entries_path(s: 'new'), 'play', 'btn-small' %>
					</td>
				</tr>
				<tr>
					<%= content_tag :td, 'Online' %>
					<td class="txtright">
						<%= content_tag :span, @presenter.online_entries.count, class: 'lead' %>
						<%= link_with_icon '', entries_path(s: 'online'), 'play', 'btn-small btn-primary', true %>
					</td>
				</tr>
				<tr>
					<%= content_tag :td, 'For Decision' %>
					<td class="txtright">
						<%= content_tag :span, @presenter.for_decision_entries.count, class: 'lead' %>
						<%= link_with_icon '', entries_path(s: 'for-decision'), 'play', 'btn-small btn-primary', true %>
					</td>
				</tr>
				<tr>
					<%= content_tag :td, 'With Orders' %>
					<td class="txtright">
						<%= content_tag :span, @presenter.with_orders_entries.count, class: 'lead' %>
						<%= link_with_icon '', entries_path(s: 'ordered'), 'play', 'btn-small' %>
					</td>
				</tr>
				<tr>
					<%= content_tag :td, 'Declined' %>
					<td class="txtright">
						<%= content_tag :span, @presenter.declined_entries.count, class: 'lead' %>
						<%= link_with_icon '', entries_path(s: 'declined'), 'play', 'btn-small' %>
					</td>
				</tr>
			</tbody>
		</table>
	</div>

	<div class="span4">
		<table class="table table-bordered table-condensed">
			<thead>
				<tr>
					<%= content_tag :th, 'Orders', colspan: 3, class: 'label label-inverse txtcenter' %>
				</tr>
			</thead>
			<tbody>
				<tr>
					<%= content_tag :td, 'New' %>
					<%= content_tag :td, @presenter.new_orders.count, class: 'txtright' %>
					<td class="txtright">
						<%= content_tag :span, (currency @presenter.new_orders.sum(:order_total), 'P '), class: 'lead' %>
						<%= link_with_icon '', orders_path(s: 'new'), 'play', 'btn-small btn-primary', true unless @presenter.new_orders.blank?%>
					</td>
				</tr>
				<tr>
					<%= content_tag :td, 'Delivered' %>
					<%= content_tag :td, @presenter.delivered.count, class: 'txtright' %>
					<td class="txtright">
						<%= content_tag :span, (currency @presenter.delivered.sum(:order_total), 'P '), class: 'lead' %>
						<%= link_with_icon '', orders_path(s: 'delivered'), 'play', 'btn-small' unless @presenter.delivered.blank?%>
					</td>
				</tr>
				<tr<%= " class=alert-error" unless @presenter.overdue.blank? %>>
					<%= content_tag :td, 'Overdue' %>
					<%= content_tag :td, @presenter.overdue.count, class: 'txtright' %>
					<td class="txtright">
						<%= content_tag :span, (currency @presenter.overdue.sum(:order_total), 'P '), class: 'lead' %>
						<%= link_with_icon '', orders_path(s: 'overdue'), 'play', 'btn-small btn-danger', true unless @presenter.overdue.blank? %>
					</td>
				</tr>
				<tr class="alert-success">
					<td colspan="3" class="txtcenter">
						<%= content_tag :b, 'Total orders through E-Bid: ' %>
						<%= content_tag :span, (currency @presenter.total_orders, 'P'), class: 'lead' %>
						<%= content_tag :i, '', class: 'icon-thumbs-up' if @presenter.total_orders > 0 %>
						<hr>
						<%= content_tag :b, 'This year only: ' %>
						<%= content_tag :span, (currency @presenter.orders_this_yr, 'P'), class: 'lead' %>
						<br>
					</td>
				</tr>
			</tbody>
		</table>
	</div>

	<div class="span5">
		<table class="table table-bordered table-condensed">
			<thead>
				<tr>
					<%= content_tag :th, 'Active Users', class: 'label label-inverse txtcenter' %>
				</tr>
			</thead>
			<tbody>
		    <% @presenter.active_users.order('current_sign_in_at DESC').each do |u| %>
		      <tr>
		        <td class="body span4">
							<%= link_to u, edit_user_path(u) %>
							<%= content_tag :span, regular_date(u.current_sign_in_at, 'short_time'), class: 'small muted' %>
						</td>
		      </tr>
		    <% end %>
			</tbody>
		</table>
	</div>
</div>