config/routes.rb
Ebid41::Application.routes.draw do


  resources :photos

  # get "sessions/new"
  # 
  # get "admin/nav"

  devise_for :users, path: :account, controllers: {sessions: "sessions"}
  resources :users, :shallow => true do
    resources :ratings, :only => :index
    resources :entries
  end

  scope 'buyer' do
    get 'dashboard' => 'buyer#dashboard', as: :buyer_dashboard
    get 'entries(/:s)' => 'buyer#entries', as: :buyer_entries
    get 'show/:id' => 'buyer#show', as: :buyer_show
    get 'show/:id/print' => 'buyer#print', as: :print_entry
    get 'reactivate/:id' => 'buyer#reactivate', as: :buyer_reactivate
    get 'orders(/:s(/:id))' => 'buyer#orders', as: :buyer_orders
    get 'fees(/:t)' => 'buyer#fees', as: :buyer_fees
    get 'messages(/:t)' => 'buyer#messages', as: :buyer_messages
    get 'surrender/:id' => 'buyer#surrender', as: :surrender_parts
    post 'surrender_letter/:id' => 'buyer#surrender_letter', as: :surrender_letter
  end

  scope 'seller' do
    get 'dashboard' => 'seller#dashboard', as: :seller_dashboard
    get 'entries(/:s)' => 'seller#entries', as: :seller_entries
    get 'worksheet' => 'seller#worksheet', as: :seller_worksheet
    get 'show/:id' => 'seller#show', as: :seller_show
    get 'bids' => 'seller#bids', as: :seller_bids
    get 'orders(/:s(/:id))' => 'seller#orders', as: :seller_orders
    get 'fees(/:t)' => 'seller#fees', as: :seller_fees
    get 'messages(/:t)' => 'seller#messages', as: :seller_messages
  end
  
  scope 'admin' do
    get 'dashboard' => 'admin#dashboard', as: :admin_dashboard
    get 'update_ratios' => 'admin#update_ratios', as: :update_ratios
    get 'expire_entries' => 'admin#expire_entries', as: :expire_entries
    get 'tag_payments' => 'admin#tag_payments', as: :tag_payments
    get 'send_payment_reminder' => 'admin#send_payment_reminder', as: :send_payment_reminder
    get 'delivery_reminder' => 'admin#delivery_reminder', as: :delivery_reminder
    get 'fix' => 'admin#fix', as: :fix
  end


  get "cart/add"
  get "cart/remove"
  get "cart/clear"

  resources :variances, only: :index do
    get :summarize, on: :collection
  end
  resources :entries, shallow: true do
    member do
      get :put_online
      get :reveal
      get :relist
      get :reactivate
      get :rebid
      get :print
      get :add_photos
      get :attach_photos
      put :save_photos
    end
    resources :variances, except: :index
  end

  resources :var_items
  resources :var_companies do
    get :add, on: :collection
    get :close, on: :collection
  end

  scope 'fees' do
    get '/:t' => 'fees#index', as: :fees
    get '/:t/print' => 'fees#print', as: :print_fees
  end
  resources :fees

  resources :messages do
    collection do
      get :view
      get :close
    end
 end

  resources :orders do
    member do
      get :accept
      get :change_status
      put :buyer_paid
      get :print
      get :cancel
      put :confirm_cancel
      get :uncancel
      put :confirm_uncancel
    end
    collection do
      get :auto_paid
    end
    resources :ratings
  end
  resources :ratings, shallow: true do
    get :auto, on: :collection
  end

  resources :bids do
    collection do
      post :accept
    end
    get :revise, on: :member
  end

  resources :line_items do
    collection do
      get :add
      get :cancel
      get :add_specs
      post :save_specs
    end
  end

  resources :profiles

  resources :ranks

  resources :branches

  resources :companies do
    get :selected, on: :member
  end

  resources :car_parts do
    collection do
      get :search
      # get :add_more
      get :cancel
    end
  end


  resources :cities

  resources :car_variants do
    member do
      get :transfer
      put :confirm_transfer
    end
  end

  resources :car_brands do
    get :selected, on: :member
  end
  
  resources :car_models do
    get :selected, on: :member
  end
  
  # authenticated :user do
  #   root :to => 'home#index'
  # end
  root :to => 'home#index'
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name, :nickname, :primary_role, :trial_start, :trial_end, 
  :metering_date, :perf_ratio, :friend_ids

  belongs_to :role, class_name: "Role", foreign_key: "primary_role"
  # belongs_to :primary_role, class_name: "Role", foreign_key: "primary_role"

  has_many :profiles
  has_many :users, through: :profiles
  has_many :branches, dependent: :destroy#, through: :profiles
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :entries
  has_many :orders
  has_many :seller_companies, through: :orders
  has_many :messages
  has_many :user_companies, through: :messages
  has_many :receiver_companies, through: :messages
  has_many :buyer_companies, through: :fees
  has_many :seller_companies, through: :fees
  has_many :variances, dependent: :destroy
  
  RATIO_DATE = Time.now.beginning_of_year #'2011-04-16'.to_datetime #
  

  def to_s
    nickname
  end
  
  def pr_label
    case primary_role
    when 2 then 'Ordering Ratio'
    when 3 then 'Bidding Ratio'
    else 'Performance Ratio'
    end
  end
  
  def compute_buyer_ratio
    es ||= entries.where('created_at >= ?', RATIO_DATE)
    line_items ||= LineItem.with_bids.where(entry_id: es)
    if line_items.count > 0
      parts_ordered = line_items.where('order_id IS NOT NULL').count
      self.perf_ratio = (BigDecimal("#{parts_ordered}")/BigDecimal("#{line_items.count}")).to_f * 100
    else
      self.perf_ratio = 0
    end
  end
  
  def compute_seller_ratio
    # entries = Entry.joins{company.friends}.where(:friendships => { :friend_id => self.id})
    parts_bided = users.map{|user| user.bids.where('bids.created_at >= ?', RATIO_DATE).collect(&:line_item_id).uniq.count}.sum
    line_items = LineItem.where('line_items.created_at >= ?', RATIO_DATE).count
    self.perf_ratio = (BigDecimal("#{parts_bided}")/BigDecimal("#{line_items}")).to_f * 100
  end
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  load_and_authorize_resource

  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
    @friends = @company.friends
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(params[:company])
    if @company.save
      redirect_to @company, :notice => "Successfully created company."
    else
      render :action => 'new'
    end
  end

  def edit
    store_location
    @company = Company.find(params[:id])
  end

  def update
    # raise params.to_yaml
    @company = Company.find(params[:id])
    if @company.update_attributes(params[:company])
      flash[:notice] = "Successfully updated company."
      redirect_back_or_default @company
    else
      render :action => 'edit'
    end
  end

  def destroy
    @company = Company.find(params[:id])
    if @company.entries.present? || @company.bids.present?
      @company.destroy # WARNING: should not DESTROY IF WITH ENTRIES/BIDS
    else
      
    end
    redirect_to companies_url, :notice => "Successfully destroyed company."
  end
  
  def selected
    @branches = Branch.where(company_id: params[:id]).order(:name)
  end
  
  
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= simple_form_for @company, :html => { :class => 'form-horizontal' } do |f| %>
	<div class="span5">
	  <%= f.input :name %>
	  <%= f.input :nickname %>
		<% if can? :access, :all %>
		  <%= f.association :role %>
		  <%= f.input :trial_start, as: :string, input_html: { size: 25, class: 'datepicker'} %>
		  <%= f.input :trial_end, as: :string, input_html: { size: 25, class: 'datepicker'} %>
		  <%= f.input :metering_date, as: :string, input_html: { size: 25, class: 'datepicker'} %>
		<% else %>
		  <%= f.association :role, disabled: true %>
		<% end %>
	  <%= f.input :perf_ratio, disabled: true %>
	</div>
	<div class="span5">
		<%= f.association :friends, as: :check_boxes, collection: Company.where("id != 1 AND primary_role != #{@company.primary_role}").order(:name) if @company.primary_role.present? %>
	</div>
  <div class="well span12 txtright">
    <%= link_to 'Cancel', :back, :class => 'btn' %>
    <%= f.button :submit, :class => 'btn-primary' %>
  </div>
<% end %>

<% content_for :javascripts do %>
	<% stylesheet 'blitzer/jquery-ui-1.8.6.custom' %>
	$(function() {
		$('.datepicker').each(function(){
		    $(this).datepicker({ 
						dateFormat: "yy-mm-dd",
						maxDate: 0,
						numberOfMonths: 2
				});
		});
	});
<% end %>

app/views/companies/_selected.html.erb
<%= content_tag :option, '', :value => nil  %>
<% for branch in @branches %>
	<%= content_tag :option, branch.name, :value => branch.id  %>
<% end %>

app/views/companies/edit.html.erb
<%- model_class = @company.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companies/index.html.erb
<% title 'Companies' %>
<div class="txtright">
	<%= link_to 'Add Company', new_company_path, :class => 'btn btn-primary btn-large' %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
		  <th>Primary Role</th>
		  <th>Rating</th>
		  <th class="txtcenter">Friends</th>
		  <th class="txtcenter">Users</th>
		  <th class="txtcenter">Perf Ratio</th>
      <th class="txtright">Actions</th>
    </tr>
  </thead>
  <tbody>
		<% @companies.group_by(&:primary_role).each do |pr, cs| %>
    <% cs.each do |company| %>
      <tr>
        <td><%= company.id %></td>
        <td><%= link_to company.name, company_path(company) %></td>
		    <td><%= company.role.name if company.primary_role %></td>
		    <td><%= star_images(Rating.where(ratee_id: company.users).average('stars').to_f) if company.primary_role %></td>
				<td class="txtcenter"><%= company.friends.size %></td>
				<td class="txtcenter"><%= company.users.size %></td>
		    <td class="txtcenter"><%= percentage company.perf_ratio, 2 %></td>
        <td class="txtright">
          <%= link_to 'Edit', edit_company_path(company), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', company_path(company), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
		<% end %>
  </tbody>
</table>

app/views/companies/new.html.erb
<%- model_class = @company.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companies/selected.js.erb
$('#branches select, select#branches').html("<%= escape_javascript(render 'companies/selected') %>");
$('.loading').remove();

app/views/companies/show.html.erb
<% title @company.name %>

<div class="row">
	<div class="span2">
		<%= content_tag :h5, @company.pr_label %>
		<%= content_tag :h1,number_to_percentage(@company.perf_ratio, precision: 2), class: 'marketing-byline' %>
	</div>
	<div class="span6">
		<%= content_tag :h5, 'Friends' %>
		<% if @friends.present?  %>
			<ol class="small">
				<% for friend in @friends %>
					<li class="friend"><%= friend.name %></li>
				<% end %>
			</ol>	
		<% else %>
			<p class="lead">
				None. <small><%= link_to 'Edit', edit_company_path(@company) %></small> to add some friends.
			</p>
		<% end %>
	</div>
	
	<div class="pull-right">
	  <%= link_to 'Edit', edit_company_path(@company), :class => 'btn' %>
	  <%= link_to 'Delete', company_path(@company), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' if can? :access, :all %>
		<%= link_to 'Companies', companies_path, class: 'btn' if can? :acces, :all %>
	</div>
</div>


<%= content_tag :h2, 'Registered Branches' %>
<table class="table table-condensed table-bordered">
	<thead>
		<tr>
			<%#= content_tag :th, 'Branch Name', class: 'lead' %>
			<%= content_tag :th, class: 'lead', rowspan: 2 do %>
				<%= content_tag :p,'Branch Name' %>
				<%= content_tag :p, link_to('Add Branch', new_branch_path(c: @company.id), class: 'btn btn-primary btn-mini') %>
			<% end %>
			<%= content_tag :th, 'Users', colspan: 4, class: 'lead txtcenter' %>
		</tr>
		<tr>
			<%= content_tag :th, 'Enabled' %>
			<%= content_tag :th, 'Full Name' %>
			<%= content_tag :th, 'Username' %>
			<%= content_tag :th %>
		</tr>
	</thead>
	<tbody>
		<% for branch in @company.branches %>
			<tr>
				<%= content_tag :td, class: 'span4', rowspan: branch.users.present? ? branch.users.size + 1 : nil do %>
					<address>
						<%= content_tag :strong, branch.name %><br/>
						<small>
							<%= branch.address1 %>
							<%= "<br/> #{branch.address2}".html_safe if branch.address2 %><br>
							<em>
								Approving Officer: 
								<%= content_tag :strong, branch.approver %>
							</em>
						</small>
					</address>
					<%= link_to 'Edit Branch', edit_branch_path(branch), class: 'btn btn-mini btn-warning' %>
					<%= link_to 'Add User', new_user_path(c: @company.id, b: branch.id), class: 'btn btn-mini' unless branch.users.blank?%>
				<% end %>
				<% if branch.users.blank? %>
					<%= content_tag :td, link_to('Add User', new_user_path(c: @company.id, b: branch.id), class: 'btn'), colspan: 4 %>
				<% end %>
			</tr>
				<% for user in branch.users.joins(:profile).order('profiles.first_name') %>
					<tr>
						<td><%= content_tag :span, user.enabled? ? 'ON' : 'OFF', class: "label #{user.enabled? ? 'label-success' : nil }" %></td>
						<td><%= user.profile %></td>
						<td><%= link_to user, user %></td>
						<td class="txtright"><%= link_to 'Edit', edit_user_path(user, c: @company.id, b: branch.id), class: 'btn btn-mini' %></td>
					</tr>
				<% end %>
		<% end %>
	</tbody>
</table>