config/routes.rb
Ebid41::Application.routes.draw do


  resources :photos

  # get "sessions/new"
  # 
  # get "admin/nav"

  devise_for :users, path: :account, controllers: {sessions: "sessions"}
  resources :users, :shallow => true do
    resources :ratings, :only => :index
    resources :entries
  end

  scope 'buyer' do
    get 'dashboard' => 'buyer#dashboard', as: :buyer_dashboard
    get 'entries(/:s)' => 'buyer#entries', as: :buyer_entries
    get 'show/:id' => 'buyer#show', as: :buyer_show
    get 'show/:id/print' => 'buyer#print', as: :print_entry
    get 'reactivate/:id' => 'buyer#reactivate', as: :buyer_reactivate
    get 'orders(/:s(/:id))' => 'buyer#orders', as: :buyer_orders
    get 'fees(/:t)' => 'buyer#fees', as: :buyer_fees
    get 'messages(/:t)' => 'buyer#messages', as: :buyer_messages
    get 'surrender/:id' => 'buyer#surrender', as: :surrender_parts
    post 'surrender_letter/:id' => 'buyer#surrender_letter', as: :surrender_letter
  end

  scope 'seller' do
    get 'dashboard' => 'seller#dashboard', as: :seller_dashboard
    get 'entries(/:s)' => 'seller#entries', as: :seller_entries
    get 'worksheet' => 'seller#worksheet', as: :seller_worksheet
    get 'show/:id' => 'seller#show', as: :seller_show
    get 'bids' => 'seller#bids', as: :seller_bids
    get 'orders(/:s(/:id))' => 'seller#orders', as: :seller_orders
    get 'fees(/:t)' => 'seller#fees', as: :seller_fees
    get 'messages(/:t)' => 'seller#messages', as: :seller_messages
  end
  
  scope 'admin' do
    get 'dashboard' => 'admin#dashboard', as: :admin_dashboard
    get 'update_ratios' => 'admin#update_ratios', as: :update_ratios
    get 'expire_entries' => 'admin#expire_entries', as: :expire_entries
    get 'tag_payments' => 'admin#tag_payments', as: :tag_payments
    get 'send_payment_reminder' => 'admin#send_payment_reminder', as: :send_payment_reminder
    get 'delivery_reminder' => 'admin#delivery_reminder', as: :delivery_reminder
    get 'fix' => 'admin#fix', as: :fix
  end


  get "cart/add"
  get "cart/remove"
  get "cart/clear"

  resources :variances, only: :index do
    get :summarize, on: :collection
  end
  resources :entries, shallow: true do
    member do
      get :put_online
      get :reveal
      get :relist
      get :reactivate
      get :rebid
      get :print
      get :add_photos
      get :attach_photos
      put :save_photos
    end
    resources :variances, except: :index
  end

  resources :var_items
  resources :var_companies do
    get :add, on: :collection
    get :close, on: :collection
  end

  scope 'fees' do
    get '/:t' => 'fees#index', as: :fees
    get '/:t/print' => 'fees#print', as: :print_fees
  end
  resources :fees

  resources :messages do
    collection do
      get :view
      get :close
    end
 end

  resources :orders do
    member do
      get :accept
      get :change_status
      put :buyer_paid
      get :print
      get :cancel
      put :confirm_cancel
      get :uncancel
      put :confirm_uncancel
    end
    collection do
      get :auto_paid
    end
    resources :ratings
  end
  resources :ratings, shallow: true do
    get :auto, on: :collection
  end

  resources :bids do
    collection do
      post :accept
    end
    get :revise, on: :member
  end

  resources :line_items do
    collection do
      get :add
      get :cancel
      get :add_specs
      post :save_specs
    end
  end

  resources :profiles

  resources :ranks

  resources :branches

  resources :companies do
    get :selected, on: :member
  end

  resources :car_parts do
    collection do
      get :search
      # get :add_more
      get :cancel
    end
  end


  resources :cities

  resources :car_variants do
    member do
      get :transfer
      put :confirm_transfer
    end
  end

  resources :car_brands do
    get :selected, on: :member
  end
  
  resources :car_models do
    get :selected, on: :member
  end
  
  # authenticated :user do
  #   root :to => 'home#index'
  # end
  root :to => 'home#index'
end

app/models/car_brand.rb
class CarBrand < ActiveRecord::Base
  attr_accessible :car_origin_id, :name
  
  belongs_to :car_origin
  has_many :car_models, dependent: :destroy
  has_many :car_variants, dependent: :destroy
  has_many :cart_entries
  has_many :entries
  has_many :bids
    
  validates_presence_of :name
    
  def to_s
    name
  end

end

app/controllers/car_brands_controller.rb
class CarBrandsController < ApplicationController
  def index
    @car_brands = CarBrand.includes(:car_origin).order('car_origin_id DESC, name ASC').paginate(page: params[:page], per_page: 15)
  end

  def show
    @car_brand = CarBrand.find(params[:id], include: [:car_models => :car_variants])
  end

  def new
    @car_brand = CarBrand.new
  end

  def create
    @car_brand = CarBrand.new(params[:car_brand])
    if @car_brand.save
      redirect_to @car_brand, :notice => "Successfully created car brand."
    else
      render :action => 'new'
    end
  end

  def edit
    @car_brand = CarBrand.find(params[:id])
  end

  def update
    @car_brand = CarBrand.find(params[:id])
    if @car_brand.update_attributes(params[:car_brand])
      redirect_to @car_brand, :notice  => "Successfully updated car brand."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @car_brand = CarBrand.find(params[:id])
    @car_brand.destroy
    redirect_to car_brands_url, :notice => "Successfully destroyed car brand."
  end

  def selected
    @car_models = CarModel.where(car_brand_id: params[:id]).order(:name)
  end
end

app/helpers/car_brands_helper.rb
module CarBrandsHelper
end

app/views/car_brands/_form.html.erb
<%= simple_form_for @car_brand, :html => { :class => 'form-horizontal' } do |f| %>
	<%= f.association :car_origin %>
  <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                car_brands_path, :class => 'btn' %>
  </div>
<% end %>

app/views/car_brands/_selected.html.erb
<%= content_tag :option, '', :value => nil  %>
<% for car_model in @car_models %>
	<%= content_tag :option, car_model.name, :value => car_model.id  %>
<% end %>

app/views/car_brands/edit.html.erb
<%- model_class = @car_brand.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human.titleize}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/car_brands/index.html.erb
<% title 'Car Brands' %>

<%= link_to 'New', new_car_brand_path, :class => 'btn btn-large btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Origin</th>
      <th>Name</th>
      <th class="txtcenter">Models</th>
      <th class="txtcenter">Entries Count</th>
      <th class="txtright">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @car_brands.group_by(&:car_origin).each do |orgin, car_brands| %>
		<% car_brands.each do |car_brand| %>
      <tr>
        <td><%= car_brand.id %></td>
        <td><%= car_brand.car_origin if car_brand.car_origin.present? %></td>
        <td><%= link_to car_brand.name, car_brand_path(car_brand) %></td>
        <td class="txtcenter"><%= car_brand.car_models.size %></td>
        <td class="txtcenter"><%#= car_brand.entries.count %></td>
        <td class="txtright">
					<%= link_to 'Show', car_brand, class: 'btn btn-mini' %>
          <%= link_to 'Edit', edit_car_brand_path(car_brand), class: 'btn btn-mini' %>
          <%= link_to 'Destroy', car_brand_path(car_brand), :method => :delete, :confirm => 'Are you sure?', class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
		<% end %>
  </tbody>
</table>

<%= will_paginate %>

app/views/car_brands/new.html.erb
<%- model_class = @car_brand.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human.titleize}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/car_brands/selected.js.erb
$('div#veh-variant span.label').remove();
$('div#veh-model select, select#veh-model').html("<%= j(render 'car_brands/selected') %>");
$('.loading').remove();

app/views/car_brands/show.html.erb
<% title "#{@car_brand} - #{pluralize @car_brand.car_models.size, 'model'}" %>

<div class="well">
  <%= link_to 'Edit', edit_car_brand_path(@car_brand), :class => 'btn' %>
  <%= link_to 'Delete', car_brand_path(@car_brand), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
  <%= link_to 'Brands', car_brands_path, :class => 'btn pull-right'  %>
</div>

<table class="table">
	<thead>
		<tr>
			<th>Model</th>
			<th>Variants</th>
			<th class="txtcenter">Entries</th>
			<th></th>
		</tr>
	</thead>
	<tbody>

			<% @car_brand.car_models.order(:name).each do |cmodel| %>
				<tr>
					<% if cmodel.car_variants.size > 0 %>
					<td class="span4" rowspan="<%= cmodel.car_variants.size + 1 %>">
					<% else %>
					<td class="span4">
					<% end %>
						<%= content_tag :h3, link_to(cmodel, cmodel) %>
						<%= link_to 'Edit', edit_car_model_path(cmodel), class: 'btn btn-mini' %>
						<%= link_to 'Delete', car_model_path(cmodel), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
					</td>
				<% if cmodel.car_variants.size < 1 %>

					<%= content_tag :td, colspan: 3 do %>
						<%= link_to 'Add Variant', new_car_variant_path, class: 'btn btn-mini btn-primary' %>
					<% end %>

				</tr>

				<% else %>

				</tr>

				<% cmodel.car_variants.order(:name).each do |variant| %>
					<tr>
						<%= content_tag :td, link_to(variant.name, variant), class: 'span3' %>
						<%= content_tag :td, variant.entries.size, class: "span1 txtcenter#{' highlight lead' if variant.entries.size > 0}" %>
						<td>
							<%= link_to 'Edit', edit_car_variant_path(variant), class: 'btn btn-mini' %>
							<%= link_to 'Delete', car_variant_path(variant), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' unless variant.entries.size > 0 %>
						</td>
					</tr>
				<% end %>

				<% end %>
			<% end %>

	</tbody>
</table>